### ISSUE TITLE
When will be the rest notes of chapter 3?

### ISSUE THREAD

**Issue by ghosthamlet** [hadrienj/deepLearningBook-Notes#13]
Hi, @hadrienj, Thanks for your crystal clear notes! I think your notes are more clear than most textbooks, When will you write the notes for 3.6-3.14 of chapter 3?

**Comment by hadrienj** [comment]
@ghosthamlet Thanks a lot for your comment! This is very encouraging!
I hope to do this end of ch03 in a few months. I currently focus on the book "Essential Math for Data Science". 
Thanks!

**Comment by ghosthamlet** [comment]
This will be a wonderful book. Wish it will have a ebook version, then i will buy it.

**Comment by hadrienj** [comment]
Hi @ghosthamlet, just to notify you about the release of [Essential Book for Data Science](https://www.essentialmathfordatascience.com/)!

**Comment by ghosthamlet** [comment]
@hadrienj Thanks, I just bought it this morning. But I don't understand why don't you open source the book code? many books opened those code, maybe more people will buy the book, if the code is all open sourced.

**Comment by hadrienj** [comment]
@ghosthamlet Thanks a lot for your support!

I considered this option but the book code contains also all the text. I could have cut it and leave the code alone, but I though that it was not that useful without the text.

Anyway, I hope that you'll find the book useful :)

**Comment by ghosthamlet** [comment]
@hadrienj Thanks, i see it now.
