### ISSUE TITLE
output_44_0.png not accessible; link broken

### ISSUE THREAD

**Issue by armandidandeh** [hadrienj/deepLearningBook-Notes#3]
https://github.com/hadrienj/deepLearningBook-Notes/blob/master/2.9%20The%20Moore-Penrose%20Pseudoinverse/images/output_44_0.png

**Comment by hadrienj** [comment]
Hi, thank you for taking the time to fill the issue! Can you tell me where did you find the broken link?

Thanks!

**Comment by armandidandeh** [comment]
The link is in the issue I opened.
https://github.com/hadrienj/deepLearningBook-Notes and under 9. The Moore-Penrose Pseudoinverse

**Comment by hadrienj** [comment]
Thanks! It is fixed!
