### ISSUE TITLE
Extract col in "2.6 Special Kinds of Matrices and Vectors"

### ISSUE THREAD

**Issue by ghosthamlet** [hadrienj/deepLearningBook-Notes#7]
Code in Example 8:
col0 = A[:, 0].reshape(A[:, 0].shape[0], 1)
col1 = A[:, 1].reshape(A[:, 1].shape[0], 1)
row0 = A[0, :].reshape(A[0, :].shape[0], 1)
row1 = A[1, :].reshape(A[1, :].shape[0], 1)

can be more simple like:
col0 = A[:, [0]]
col1 = A[:, [1]]
row0 = A[0].reshape(A.shape[1], 1)
row1 = A[1].reshape(A.shape[1], 1)

**Comment by hadrienj** [comment]
Thank you ghosthamlet! I just updated the example!
