### ISSUE TITLE
How these schematic diagram are drawed?

### ISSUE THREAD

**Issue by PingjunChen** [hadrienj/deepLearningBook-Notes#8]
Hi, I quite like your note, and the diagram you draw looks really intuitive and comfortable. I would like to know what software you use to draw these images and any suggestions on how to draw nice looking image.

**Comment by hadrienj** [comment]
Hi,
Thanks for the feedback! I used OmniGraffle to draw the diagrams. I like it because it is quite easy to use, but unfortunately, it is not free :)

**Comment by PingjunChen** [comment]
Thanks for your reply. I would consider to buy it. Your drawing looks really comfortable...
