### ISSUE TITLE
new notes of chapter 3/4/5?

### ISSUE THREAD

**Issue by cnjsdfcy** [hadrienj/deepLearningBook-Notes#9]
Hi there, 
thanks for this great notes about linear algebra chapter in deep learning book with vivid python code. will you think about writing notes of chapter 3/4/5 to help us get better understanding of math behind AI?
Thanks.

**Comment by hadrienj** [comment]
Hi, thanks for your message! I started Chapter 3 (first article [here](https://hadrienj.github.io/posts/Probability-Mass-and-Density-Functions/)). Stay tuned for the next articles.
